# requests to be tested with REST Client

# LOGIN
POST http://localhost:5000/api/login/
Content-type: application/json

{
  "email": "momo@gmail.com",
  "password": "123456"
}


###

# GET all users
GET http://localhost:5000/api/users

###

# GET an existing user
GET http://localhost:5000/api/users/9

###

# POST a new user
POST http://localhost:5000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjksImlhdCI6MTY3MzM0OTQ5MywiZXhwIjoxNjczMzUzMDkzfQ.PEzc3ODdSlCxaLk57PXZ1pxKGISJytC_WqgEcAZ8lus
Content-Type: application/json

{
    "firstname": "allo",
    "lastname": "pupu",
    "email": "ouhou@mail.com",
    "password": "123456"
}

###

# PUT a new user
PUT http://localhost:5000/api/users/10
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjksImlhdCI6MTY3MzM0OTQ5MywiZXhwIjoxNjczMzUzMDkzfQ.PEzc3ODdSlCxaLk57PXZ1pxKGISJytC_WqgEcAZ8lus
Content-Type: application/json

{
    "firstname": "keke",
    "lastname": "pupu",
    "email": "ouhou@mail.com",
    "password": "123456"
}

###

# GET all movies
GET http://localhost:5000/api/movies

###

# GET an existing movie
GET http://localhost:5000/api/movies/9


###

# POST a new movie
POST http://localhost:5000/api/movies
Content-type: application/json

{
  "title": "Matrix",
  "director": "Brothers",
  "year": "2000",
  "color": "0",
  "duration": 240
}

###

# POST a new movie WITH authorization
POST http://localhost:5000/api/movies
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjksImlhdCI6MTY3MzM0NjE0MiwiZXhwIjoxNjczMzQ5NzQyfQ.NxM1FnjCuVICuv58nro9jgzZMKEExJjsWvjnORfsA90
Content-type: application/json

{
  "title": "Matrix",
  "director": "Brothers",
  "year": "2000",
  "color": "0",
  "duration": 240
}

###

# PUT a new movie WITH authorization
PUT http://localhost:5000/api/movies/9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjksImlhdCI6MTY3MzM0NjE0MiwiZXhwIjoxNjczMzQ5NzQyfQ.NxM1FnjCuVICuv58nro9jgzZMKEExJjsWvjnORfsA90
Content-type: application/json

{
  "title": "Platoon",
  "director": "Brothers",
  "year": "2000",
  "color": "0",
  "duration": 240
}